[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "goose-testrail"
version = "0.1.0"
description = "TestRail extension for Goose"
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
keywords = ["goose", "testrail", "testing"]
authors = [
    { name = "Your Name", email = "your.email@example.com" }
]
dependencies = [
    "testrail-api>=1.0",
    "goose-mcp>=0.1.0",
]

[project.entry-points.goose_extensions]
testrail = "goose_testrail:TestRailExtension"